# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins:             [jekyll-paginate]
paginate_path:       "page:num"

# Setup
title:               Yago Fontenla Seco
tagline:             'A bunch of random numbers'
description:         'A computer engineer mastering in AI. My brain works with coffee and music.'
url:                 https://yagouus.github.io
avatar:              https://avatars1.githubusercontent.com/u/9059328?v=4&s=460
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yago Fontenla Seco
  url:               https://twitter.com/yagouus
  email:             yago.fontenla.seco@gmail.com
  
# Custom vars
version:             1.0.0
